# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czT9Glc9kWFUrV1Ox7XFPHpyuADP-6En
"""

!git clone https://github.com/rfalnsari/03-ImageProcessing-lab3

# Commented out IPython magic to ensure Python compatibility.
# %cd 03-ImageProcessing-lab3

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np

img = cv2.imread('image.jpg')

resized = cv2.resize(img, None, fx=1.5, fy=1.5)

(h, w) = img.shape[:2]
center = (w // 2, h // 2)
matrix = cv2.getRotationMatrix2D(center, 120, 1.0)
rotated = cv2.warpAffine(img, matrix, (w, h))

M = np.float32([[1, 0.5, 0],
                [0, 1, 0]])
sheared = cv2.warpAffine(img, M, (w, h))

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

negative = 255 - gray

c = 255 / np.log(1 + np.max(gray))
log_transformed = c * np.log(1 + gray)
log_transformed = np.array(log_transformed, dtype=np.uint8)

gamma = 2.0
power = np.array(255 * (gray / 255) ** gamma, dtype=np.uint8)

cv2.imwrite('resized.jpg', resized)
cv2.imwrite('rotated.jpg', rotated)
cv2.imwrite('sheared.jpg', sheared)

cv2.imwrite('negative.jpg', negative)
cv2.imwrite('log.jpg', log_transformed)
cv2.imwrite('power.jpg', power)

print("تم التنفيذ ")

from google.colab import files

files.download('resized.jpg')
files.download('rotated.jpg')
files.download('sheared.jpg')
files.download('negative.jpg')
files.download('log.jpg')
files.download('power.jpg')